title: Danny Thacker's Portfolio
description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-minimal

email: thenumberonesonsband@gmail.com
github_username: danzilladanny
linkeedin_username: dannythacker