title: "Danny Thacker"
description: "Software Developer | Audio Engineer"
theme: jekyll-theme-minimal

email: "thenumberonesonsband@gmail.com"
github_username: https://github.com/DanzillaDanny/DanzillaDanny
linkedin_username: https://www.linkedin.com/in/danny-thacker